<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">

    <title>Contributions Report</title>

    <style>

        body {
            font-family: DejaVu Sans;
            font-size: 12px;
            color: #333;
        }

        .header {
            margin-bottom: 20px;
        }

        .title {
            font-size: 22px;
            font-weight: bold;
        }

        .subtitle {
            color: #777;
            margin-top: 4px;
        }

        .summary {
            margin: 20px 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        table th {
            background: #f3f4f6;
            text-align: left;
            padding: 10px;
            border: 1px solid #ddd;
        }

        table td {
            padding: 10px;
            border: 1px solid #ddd;
        }

        .total-box {
            margin-top: 20px;
            text-align: right;
            font-size: 16px;
            font-weight: bold;
        }

    </style>

</head>

<body>

    {{-- HEADER --}}
    <div class="header">

        <div class="title">
            Contributions Report
        </div>

        <div class="subtitle">
            Generated by {{ auth()->user()->name ?? '' }} on {{ now()->format('d M Y H:i') }}
        </div>

    </div>

    {{-- TABLE --}}
    <table>

        <thead>

            <tr>

                <th>Member</th>

                <th>Amount</th>

                <th>Type</th>

                <th>Status</th>

                <th>Date</th>

                <th>Period</th>

            </tr>

        </thead>

        <tbody>

            @foreach($contributions as $c)

                <tr>

                    <td>
                        {{ $c->borrower->full_name }}
                    </td>

                    <td>
                        KES {{ number_format($c->amount) }}
                    </td>

                    <td>
                        {{ strtoupper($c->type) }}
                    </td>

                    <td>
                        {{ strtoupper($c->status) }}
                    </td>

                    <td>
                        {{ $c->contribution_date }}
                    </td>

                    <td>
                        {{ $c->period }}
                    </td>

                </tr>

            @endforeach

        </tbody>

    </table>

    {{-- TOTAL --}}
    <div class="total-box">

        TOTAL CONTRIBUTIONS:
        KES {{ number_format($totalAmount) }}

    </div>

</body>
</html>
